# Generated by Django 4.0.6 on 2022-08-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='description',
            new_name='description_1',
        ),
        migrations.AddField(
            model_name='articles',
            name='description_2',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
