# Generated by Django 4.0.6 on 2022-08-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_products_ibu_products_alcohol_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
