# Generated by Django 4.1 on 2022-08-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botella1l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('alcohol_volume', models.FloatField(blank=True, max_length=2, null=True)),
                ('IBU', models.FloatField(blank=True, max_length=2, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('malt', models.CharField(blank=True, max_length=50, null=True)),
                ('hop', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, default=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
