# Generated by Django 4.1 on 2022-08-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_botella1l'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botella_lata_473cc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('alcohol_volume', models.FloatField(blank=True, max_length=2, null=True)),
                ('IBU', models.FloatField(blank=True, max_length=2, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('malt', models.CharField(blank=True, max_length=50, null=True)),
                ('hop', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, default=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Botella1l',
            new_name='Botella_1l',
        ),
    ]
